package main

import (
	"fmt"
	"math/rand"
)

// A list of responses that a personified version of a Linux command might give if the user was to ask how it was doing.
var responses = []string{
	"Good",
	"Eh",
	"Never been better",
	"Could be better",
	".",
	// And here are some generic responses generated by GitHub Copilot
	"Great",
	"Fantastic",
	"Awesome",
	"Doing well",
	"Just peachy",
	"Couldn't be better",
	"Feeling good",
	"Just fine",
	// Including some mildly negative responses
	"Could be worse",
	"Not so great",
	"Not so good",
	// And these were generated by directly asking ChatGPT
	"Overloaded, but managing",
	"Running smoothly",
	"Feeling a bit fragmented",
	"Optimized and ready",
	"Under heavy load, but holding up",
	"Waiting for your command",
	"Feeling deprecated",
	"Running out of memory",
	"Kernel panic... just kidding!",
	"Feeling secure and up-to-date",
	"Compiling my thoughts",
	"Feeling like a segfault waiting to happen",
	"Just rebooted, feeling fresh",
	"Experiencing some latency",
	"Feeling like a zombie process",
	"Ready to fork some processes",
	"Feeling like a core dump",
	"Just patched and feeling great",
}

func main() {
	random_number := rand.Uint32()
	response := responses[random_number%uint32(len(responses))]
	fmt.Println(response)
}
